name: Build and Push Docker Image

on:
  push:
    branches:
      - portfolio-push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sysfoo:latest .
      working-directory: ./home/runner/work/Personal-Portfolio-React/Personal-Portfolio-React/

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/sysfoo:latest
